# Data Preprocessing

In [7]:
import pandas as pd
import numpy as np
!pip install matplotlib
!pip install shap

Requirement already satisfied: matplotlib in m:\data analyst\python 3.11\lib\site-packages (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in m:\data analyst\python 3.11\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in m:\data analyst\python 3.11\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in m:\data analyst\python 3.11\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in m:\data analyst\python 3.11\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in m:\data analyst\python 3.11\lib\site-packages (from matplotlib) (2.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in m:\data analyst\python 3.11\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in m:\data analyst\python 3.11\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\roaming\python\python311\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip available: 22.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: shap in m:\data analyst\python 3.11\lib\site-packages (0.51.0)
Requirement already satisfied: numpy>=2 in m:\data analyst\python 3.11\lib\site-packages (from shap) (2.4.4)
Requirement already satisfied: scipy in m:\data analyst\python 3.11\lib\site-packages (from shap) (1.17.1)
Requirement already satisfied: scikit-learn in m:\data analyst\python 3.11\lib\site-packages (from shap) (1.8.0)
Requirement already satisfied: pandas in m:\data analyst\python 3.11\lib\site-packages (from shap) (3.0.2)
Requirement already satisfied: tqdm>=4.27.0 in m:\data analyst\python 3.11\lib\site-packages (from shap) (4.67.3)
Requirement already satisfied: packaging>20.9 in c:\users\user\appdata\roaming\python\python311\site-packages (from shap) (26.2)
Requirement already satisfied: slicer==0.0.8 in m:\data analyst\python 3.11\lib\site-packages (from shap) (0.0.8)
Requirement already satisfied: numba in m:\data analyst\python 3.11\lib\site-packages (from shap) (0.65.1)
Requirement already satisfied: llvmlite in m:\data analyst\python 3.11\lib\site-packages (from shap) (0.47.0)
Requirement already satisfied: cloudpickle in m:\data analyst\python 3.11\lib\site-packages (from shap) (3.1.2)
Requirement already satisfied: typing-extensions in c:\users\user\appdata\roaming\python\python311\site-packages (from shap) (4.15.0)
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python311\site-packages (from tqdm>=4.27.0->shap) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python311\site-packages (from pandas->shap) (2.9.0.post0)
Requirement already satisfied: tzdata in m:\data analyst\python 3.11\lib\site-packages (from pandas->shap) (2026.2)
Requirement already satisfied: joblib>=1.3.0 in m:\data analyst\python 3.11\lib\site-packages (from scikit-learn->shap) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in m:\data analyst\python 3.11\lib\site-packages (from scikit-learn->shap) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas->shap) (1.17.0)

[notice] A new release of pip available: 22.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Load dataset

In [40]:
base_data = pd.read_csv(r"C:\Users\user\Documents\GitHub\Project-2-Unified Mentor\European_Bank.csv")

In [41]:
base_data.shape

(10000, 14)

In [42]:
base_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.2 MB

In [10]:
base_data.head()

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2025,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2025,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,2025,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,2025,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

Clean Dataset

In [11]:
# remove unnecessary columns
base_data.drop(columns = ['CustomerId', 'Surname'], inplace = True)

In [12]:
base_data.head()

,Year,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2025,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2025,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,2025,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,2025,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [13]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in m:\data analyst\python 3.11\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in m:\data analyst\python 3.11\lib\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in m:\data analyst\python 3.11\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in m:\data analyst\python 3.11\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in m:\data analyst\python 3.11\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip available: 22.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
# Encode Categorical Variables
# for Gender Label encoding is used as it has only two categories
from sklearn.preprocessing import LabelEncoder
base_data['Gender'] = LabelEncoder().fit_transform(base_data['Gender'])

# for Geography One hot encoding is used, more than two categories are present
base_data = pd.get_dummies(base_data, columns = ['Geography'], drop_first = True)

In [15]:
base_data.head() # France can be predicted by the absence of Germany and Spain # Female is 0 and Male is 1.

,Year,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,2025,619,0,42,2,0.00,1,1,1,101348.88,1,False,False
1,2025,608,0,41,1,83807.86,1,0,1,112542.58,0,False,True
2,2025,502,0,42,8,159660.80,3,1,0,113931.57,1,False,False
3,2025,699,0,39,1,0.00,2,0,0,93826.63,0,False,False
4,2025,850,0,43,2,125510.82,1,1,1,79084.10,0,False,True

In [16]:
# FEATURE ENGINEERING
base_data['Balance_to_Salary_ratio'] = base_data['Balance'] / base_data['EstimatedSalary']

base_data['Product_Density_Indicator'] = base_data['NumOfProducts']/ base_data['Age']

base_data['Engagement_product_indicator'] = base_data['NumOfProducts']*2 + base_data['HasCrCard'] + base_data['IsActiveMember']

base_data['Age_tenure_interaction'] = base_data['Age']*base_data['Tenure']

In [17]:
base_data.head()

,Year,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Balance_to_Salary_ratio,Product_Density_Indicator,Engagement_product_indicator,Age_tenure_interaction
0,2025,619,0,42,2,0.00,1,1,1,101348.88,1,False,False,0.000000,0.023810,4,84
1,2025,608,0,41,1,83807.86,1,0,1,112542.58,0,False,True,0.744677,0.024390,3,41
2,2025,502,0,42,8,159660.80,3,1,0,113931.57,1,False,False,1.401375,0.071429,7,336
3,2025,699,0,39,1,0.00,2,0,0,93826.63,0,False,False,0.000000,0.051282,4,39
4,2025,850,0,43,2,125510.82,1,1,1,79084.10,0,False,True,1.587055,0.023256,4,86

In [18]:
# Scale Numerical Features
from sklearn.preprocessing  import StandardScaler

cols = ['CreditScore', 'Age', 'Balance', 'EstimatedSalary', 'Balance_to_Salary_ratio']

scalar = StandardScaler()

base_data[cols] = scalar.fit_transform(base_data[cols])

In [19]:
base_data.head()

,Year,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Balance_to_Salary_ratio,Product_Density_Indicator,Engagement_product_indicator,Age_tenure_interaction
0,2025,-0.326221,0,0.293517,2,-1.225848,1,1,1,0.021886,1,False,False,-0.035804,0.023810,4,84
1,2025,-0.440036,0,0.198164,1,0.117350,1,0,1,0.216534,0,False,True,-0.028930,0.024390,3,41
2,2025,-1.536794,0,0.293517,8,1.333053,3,1,0,0.240687,1,False,False,-0.022868,0.071429,7,336
3,2025,0.501521,0,0.007457,1,-1.225848,2,0,0,-0.108918,0,False,False,-0.035804,0.051282,4,39
4,2025,2.063884,0,0.388871,2,0.785728,1,1,1,-0.365276,0,False,True,-0.021154,0.023256,4,86

Churn Rate

In [20]:
churn_rate = base_data['Exited'].mean()*100
print(f"Churn Rate: {churn_rate:.2f}%")

Churn Rate: 20.37%

# Training and Testing

In [21]:
# Features and Target
x = base_data.drop('Exited', axis = 1)
y = base_data['Exited']

# Train Test Split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42, stratify = y)

# Scale Numerical Features
num_cols = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary', 'Balance_to_Salary_ratio',
            'Product_Density_Indicator', 'Engagement_product_indicator', 'Age_tenure_interaction']
scalar = StandardScaler()
x_train[num_cols] = scalar.fit_transform(x_train[num_cols])
x_test[num_cols] = scalar.transform(x_test[num_cols])

Logistic Regression

In [22]:
# Train Model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter = 1000)
model.fit(x_train, y_train)

# Predictions
y_pred = model.predict(x_test)

# Evaluation
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("ROC AUC Score:", roc_auc_score(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.8075
Precision: 0.5846153846153846
Recall: 0.18673218673218672
F1 Score: 0.28305400372439476
ROC AUC Score: 0.5764169408237205
Confusion Matrix:
[[1539   54]
 [ 331   76]]
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.97      0.89      1593
           1       0.58      0.19      0.28       407

    accuracy                           0.81      2000
   macro avg       0.70      0.58      0.59      2000
weighted avg       0.77      0.81      0.77      2000

Decision Tree

In [23]:
from sklearn.tree import DecisionTreeClassifier
model2 = DecisionTreeClassifier(random_state = 42)
model2.fit(x_train, y_train)
y_pred2 = model2.predict(x_test)
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report)
print("Accuracy:", accuracy_score(y_test, y_pred2))
print("Precision:", precision_score(y_test, y_pred2))
print("Recall:", recall_score(y_test, y_pred2))
print("F1 Score:", f1_score(y_test, y_pred2))
print("ROC AUC Score:", roc_auc_score(y_test, y_pred2))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred2))
print("Classification Report:")
print(classification_report(y_test, y_pred2))

Accuracy: 0.796
Precision: 0.4988610478359909
Recall: 0.538083538083538
F1 Score: 0.5177304964539007
ROC AUC Score: 0.6999896660913609
Confusion Matrix:
[[1373  220]
 [ 188  219]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.86      0.87      1593
           1       0.50      0.54      0.52       407

    accuracy                           0.80      2000
   macro avg       0.69      0.70      0.69      2000
weighted avg       0.80      0.80      0.80      2000

Random Forest

In [24]:
from sklearn.ensemble import RandomForestClassifier
model3 = RandomForestClassifier(random_state = 42)
model3.fit(x_train, y_train)
y_pred3 = model3.predict(x_test)

from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report)
print("Accuracy:", accuracy_score(y_test, y_pred3))
print("Precision:", precision_score(y_test, y_pred3))
print("Recall:", recall_score(y_test, y_pred3))
print("F1 Score:", f1_score(y_test, y_pred3))
print("ROC AUC Score:", roc_auc_score(y_test, y_pred3))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred3))
print("Classification Report:")
print(classification_report(y_test, y_pred3))

Accuracy: 0.864
Precision: 0.7848101265822784
Recall: 0.457002457002457
F1 Score: 0.577639751552795
ROC AUC Score: 0.712493695544543
Confusion Matrix:
[[1542   51]
 [ 221  186]]
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1593
           1       0.78      0.46      0.58       407

    accuracy                           0.86      2000
   macro avg       0.83      0.71      0.75      2000
weighted avg       0.86      0.86      0.85      2000

Gradient Boosting

In [25]:
from sklearn.ensemble import GradientBoostingClassifier
model4 = GradientBoostingClassifier(random_state = 42)
model4.fit(x_train, y_train)
y_pred4 = model4.predict(x_test)

from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report)
print("Accuracy:", accuracy_score(y_test, y_pred4))
print("Precision:", precision_score(y_test, y_pred4))
print("Recall:", recall_score(y_test, y_pred4))
print("F1 Score:", f1_score(y_test, y_pred4))
print("ROC AUC Score:", roc_auc_score(y_test, y_pred4))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred4))
print("Classification Report:")
print(classification_report(y_test, y_pred4))

Accuracy: 0.87
Precision: 0.7905138339920948
Recall: 0.4914004914004914
F1 Score: 0.6060606060606061
ROC AUC Score: 0.729064966353102
Confusion Matrix:
[[1540   53]
 [ 207  200]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1593
           1       0.79      0.49      0.61       407

    accuracy                           0.87      2000
   macro avg       0.84      0.73      0.76      2000
weighted avg       0.86      0.87      0.86      2000

# Comparison Table

In [27]:
Comparison_table = pd.read_excel(r"C:\Users\user\Documents\GitHub\Project-2-Unified Mentor\Comparison Table for Different ML models.xlsx")

In [28]:
Comparison_table.head()

                 Model  Accuracy  Precision    Recall        F1   ROC-AUC
0  Logistic Regression    0.8075   0.584615  0.186732  0.283054  0.576417
1        Decision Tree    0.7960   0.498861  0.538084  0.517730  0.699990
2        Random Forest    0.8640   0.784810  0.457002  0.577640  0.712494
3    Gradient Boosting    0.8700   0.790514  0.491400  0.606061  0.729065

In [29]:
# Clearly GRADIENT BOOSTING CLASSIFIER is the best model for this dataset.

Important Features for Gradient Boosting Classifier

In [30]:
important_features = pd.DataFrame({'Feature': x.columns, 'Importance': model4.feature_importances_})
important_features = important_features.sort_values(by = 'Importance', ascending = False)

print(important_features)

                         Feature  Importance
13     Product_Density_Indicator    0.289509
6                  NumOfProducts    0.229670
3                            Age    0.161562
8                 IsActiveMember    0.101594
10             Geography_Germany    0.054563
5                        Balance    0.049887
12       Balance_to_Salary_ratio    0.039355
14  Engagement_product_indicator    0.022221
1                    CreditScore    0.015071
9                EstimatedSalary    0.013520
2                         Gender    0.012237
15        Age_tenure_interaction    0.009405
4                         Tenure    0.000817
11               Geography_Spain    0.000563
7                      HasCrCard    0.000025
0                           Year    0.000000

CHURN PROBABILITY SCORES

In [31]:
base_data['Churn_Probability'] = model4.predict_proba(x)[:,1]

base_data.head()

,Year,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Balance_to_Salary_ratio,Product_Density_Indicator,Engagement_product_indicator,Age_tenure_interaction,Churn_Probability
0,2025,-0.326221,0,0.293517,2,-1.225848,1,1,1,0.021886,1,False,False,-0.035804,0.023810,4,84,0.058825
1,2025,-0.440036,0,0.198164,1,0.117350,1,0,1,0.216534,0,False,True,-0.028930,0.024390,3,41,0.096203
2,2025,-1.536794,0,0.293517,8,1.333053,3,1,0,0.240687,1,False,False,-0.022868,0.071429,7,336,0.915325
3,2025,0.501521,0,0.007457,1,-1.225848,2,0,0,-0.108918,0,False,False,-0.035804,0.051282,4,39,0.579596
4,2025,2.063884,0,0.388871,2,0.785728,1,1,1,-0.365276,0,False,True,-0.021154,0.023256,4,86,0.157924

Predictive Risk Scoring System

In [32]:
def risk_category(prob):
    if prob < 0.3:
        return 'Low Risk'
    elif prob < 0.7:
        return 'Medium Risk'
    else: 
        return 'High Risk'
base_data['Risk Level'] = base_data['Churn_Probability'].apply(risk_category)

In [33]:
base_data.head()

,Year,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Balance_to_Salary_ratio,Product_Density_Indicator,Engagement_product_indicator,Age_tenure_interaction,Churn_Probability,Risk Level
0,2025,-0.326221,0,0.293517,2,-1.225848,1,1,1,0.021886,1,False,False,-0.035804,0.023810,4,84,0.058825,Low Risk
1,2025,-0.440036,0,0.198164,1,0.117350,1,0,1,0.216534,0,False,True,-0.028930,0.024390,3,41,0.096203,Low Risk
2,2025,-1.536794,0,0.293517,8,1.333053,3,1,0,0.240687,1,False,False,-0.022868,0.071429,7,336,0.915325,High Risk
3,2025,0.501521,0,0.007457,1,-1.225848,2,0,0,-0.108918,0,False,False,-0.035804,0.051282,4,39,0.579596,Medium Risk
4,2025,2.063884,0,0.388871,2,0.785728,1,1,1,-0.365276,0,False,True,-0.021154,0.023256,4,86,0.157924,Low Risk

In [35]:
# saving data for dashboard
dashboard_data = base_data.to_csv(r"C:\Users\user\Documents\GitHub\Project-2-Unified Mentor\dashboard_data.csv", index = False)

In [36]:
dashboard_data = pd.read_csv(r"C:\Users\user\Documents\GitHub\Project-2-Unified Mentor\dashboard_data.csv")
dashboard_data.head()

,Year,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Balance_to_Salary_ratio,Product_Density_Indicator,Engagement_product_indicator,Age_tenure_interaction,Churn_Probability,Risk Level
0,2025,-0.326221,0,0.293517,2,-1.225848,1,1,1,0.021886,1,False,False,-0.035804,0.023810,4,84,0.058825,Low Risk
1,2025,-0.440036,0,0.198164,1,0.117350,1,0,1,0.216534,0,False,True,-0.028930,0.024390,3,41,0.096203,Low Risk
2,2025,-1.536794,0,0.293517,8,1.333053,3,1,0,0.240687,1,False,False,-0.022868,0.071429,7,336,0.915325,High Risk
3,2025,0.501521,0,0.007457,1,-1.225848,2,0,0,-0.108918,0,False,False,-0.035804,0.051282,4,39,0.579596,Medium Risk
4,2025,2.063884,0,0.388871,2,0.785728,1,1,1,-0.365276,0,False,True,-0.021154,0.023256,4,86,0.157924,Low Risk

Save MODEL FILE for Streamlit

In [37]:
import pickle
pickle.dump(model4, open("churn_model_Grad_Boost.pkl", "wb"))

# to load file later write "rb" instead of "wb"

In [38]:
# save scaler file for dashboard
pickle.dump(scalar, open("scaler.pkl", "wb"))